# Generated by Django 2.2.1 on 2019-09-25 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('description', models.TextField(null=True)),
                ('publisher', models.CharField(choices=[('DC', 'DC'), ('MARVEL', 'Marvel'), ('OTHER', 'Other')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('heroes', models.ManyToManyField(related_name='herolist', to='myapi.Hero')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
