# Generated by Django 2.2.1 on 2019-09-25 03:08

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='heroes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='heroes',
            field=models.Field(default='', verbose_name=myapi.models.Hero),
            preserve_default=False,
        ),
    ]
