# Generated by Django 2.2.1 on 2019-09-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='publisher',
            field=models.CharField(choices=[('DC', 'DC'), ('MARVEL', 'Marvel')], max_length=5, null=True),
        ),
    ]
