# Generated by Django 2.2.1 on 2019-09-25 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20190925_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='heroes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='heroes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='her', to='myapi.Hero'),
        ),
    ]
