# Generated by Django 2.2.1 on 2019-09-25 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20190925_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='heroes',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='herolist', to='myapi.Hero'),
            preserve_default=False,
        ),
    ]
